# docker-compose.yml

version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "@dm1n12#$"
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn chat_project.asgi:application -k uvicorn.workers.UvicornWorker --bind :8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
